// backend/src/routes/export.js
// Export tutorials to PDF, HTML, or DOCX

const express = require('express');
const path = require('path');
const fs = require('fs');
const PDFDocument = require('pdfkit');
const { Document, Packer, Paragraph, TextRun, ImageRun, HeadingLevel, AlignmentType } = require('docx');
const { getDb, UPLOADS_DIR } = require('../config/database');
const { requireAuth } = require('../middleware/auth');

const router = express.Router();

/**
 * Fetches tutorial + steps, verifies ownership or public access.
 */
function getTutorialData(tutorialId, userId) {
  const db = getDb();
  let tutorial;

  if (userId) {
    tutorial = db.get('SELECT * FROM tutorials WHERE id = ? AND user_id = ?', [tutorialId, userId]);
  } else {
    tutorial = db.get('SELECT * FROM tutorials WHERE id = ? AND is_public = 1', [tutorialId]);
  }

  if (!tutorial) return null;

  const steps = db.all(
    'SELECT * FROM steps WHERE tutorial_id = ? ORDER BY order_index ASC',
    [tutorial.id]
  );

  return { tutorial, steps };
}

// GET /api/export/:id/html
router.get('/:id/html', requireAuth, (req, res) => {
  const data = getTutorialData(req.params.id, req.user.id);
  if (!data) return res.status(404).json({ error: 'Tutorial not found' });

  const { tutorial, steps } = data;
  const baseUrl = `${req.protocol}://${req.get('host')}`;

  const stepsHtml = steps.map((step, i) => {
    const screenshotHtml = step.screenshot_url
      ? `<img src="${baseUrl}${step.screenshot_url}" alt="Step ${i + 1} screenshot" style="max-width:100%;border:1px solid #ddd;border-radius:8px;margin-bottom:12px;" />`
      : '';

    return `
      <div style="margin-bottom:40px;padding:24px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;">
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:16px;">
          <span style="background:#4F46E5;color:white;width:32px;height:32px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:bold;font-size:14px;flex-shrink:0;text-align:center;line-height:32px;">${i + 1}</span>
          <h3 style="margin:0;font-size:16px;color:#111827;">${escapeHtml(step.instruction)}</h3>
        </div>
        ${screenshotHtml}
        ${step.page_url ? `<p style="font-size:12px;color:#6b7280;margin:8px 0 0;">URL: ${escapeHtml(step.page_url)}</p>` : ''}
      </div>`;
  }).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(tutorial.title)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background:#f9fafb; color:#111827; margin:0; padding:0; }
    .container { max-width:800px; margin:0 auto; padding:40px 20px; }
    .header { margin-bottom:40px; padding-bottom:24px; border-bottom:2px solid #e5e7eb; }
    .header h1 { font-size:28px; font-weight:700; color:#111827; margin:0 0 8px; }
    .header p { font-size:16px; color:#6b7280; margin:0; }
    .meta { font-size:13px; color:#9ca3af; margin-top:8px; }
    .footer { margin-top:40px; padding-top:24px; border-top:1px solid #e5e7eb; text-align:center; font-size:13px; color:#9ca3af; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${escapeHtml(tutorial.title)}</h1>
      ${tutorial.description ? `<p>${escapeHtml(tutorial.description)}</p>` : ''}
      <p class="meta">Generated by SnapGuide &bull; ${steps.length} steps &bull; ${new Date(tutorial.created_at).toLocaleDateString()}</p>
    </div>
    ${stepsHtml}
    <div class="footer">
      <p>Created with <strong>SnapGuide</strong> &mdash; Automatic Tutorial Generator</p>
    </div>
  </div>
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html');
  res.setHeader('Content-Disposition', `attachment; filename="${sanitizeFilename(tutorial.title)}.html"`);
  res.send(html);
});

// GET /api/export/:id/pdf
router.get('/:id/pdf', requireAuth, (req, res) => {
  const data = getTutorialData(req.params.id, req.user.id);
  if (!data) return res.status(404).json({ error: 'Tutorial not found' });

  const { tutorial, steps } = data;

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${sanitizeFilename(tutorial.title)}.pdf"`);

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  doc.pipe(res);

  // Title page header
  doc.rect(0, 0, doc.page.width, 120).fill('#4F46E5');
  doc.fillColor('white').fontSize(26).font('Helvetica-Bold').text(tutorial.title, 50, 40, { width: doc.page.width - 100 });

  if (tutorial.description) {
    doc.fontSize(13).font('Helvetica').text(tutorial.description, 50, 80, { width: doc.page.width - 100 });
  }

  doc.moveDown(4);

  // Meta line
  doc.fillColor('#6b7280').fontSize(11).font('Helvetica')
    .text(`${steps.length} step${steps.length !== 1 ? 's' : ''} • Generated ${new Date().toLocaleDateString()} • SnapGuide`, { align: 'center' });

  doc.moveDown(2);

  // Steps
  steps.forEach((step, i) => {
    // Step header bar
    doc.rect(50, doc.y, doc.page.width - 100, 28).fill('#EEF2FF');
    doc.fillColor('#4F46E5').fontSize(11).font('Helvetica-Bold')
      .text(`Step ${i + 1}`, 60, doc.y - 22);
    doc.moveDown(0.5);

    // Instruction
    doc.fillColor('#111827').fontSize(13).font('Helvetica-Bold')
      .text(step.instruction, { indent: 10 });
    doc.moveDown(0.5);

    // Screenshot
    if (step.screenshot_url) {
      const imgPath = path.join(UPLOADS_DIR, path.basename(step.screenshot_url));
      if (fs.existsSync(imgPath)) {
        try {
          const maxWidth = doc.page.width - 100;
          doc.image(imgPath, { fit: [maxWidth, 300], align: 'center' });
          doc.moveDown(0.5);
        } catch (e) {
          // Skip image if unreadable
        }
      }
    }

    // Page URL
    if (step.page_url) {
      doc.fillColor('#9ca3af').fontSize(10).font('Helvetica')
        .text(`URL: ${step.page_url}`, { indent: 10 });
    }

    doc.moveDown(1.5);

    // Add new page if near bottom
    if (doc.y > doc.page.height - 150 && i < steps.length - 1) {
      doc.addPage();
    }
  });

  doc.end();
});

// GET /api/export/:id/docx
router.get('/:id/docx', requireAuth, async (req, res) => {
  const data = getTutorialData(req.params.id, req.user.id);
  if (!data) return res.status(404).json({ error: 'Tutorial not found' });

  const { tutorial, steps } = data;

  const children = [
    new Paragraph({
      text: tutorial.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }),
  ];

  if (tutorial.description) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: tutorial.description, color: '4b5563', size: 24 })],
        spacing: { after: 400 },
      })
    );
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `${steps.length} steps • Generated ${new Date().toLocaleDateString()} • SnapGuide`, color: '9ca3af', size: 20 }),
      ],
      spacing: { after: 600 },
    })
  );

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];

    children.push(
      new Paragraph({
        text: `Step ${i + 1}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 100 },
      }),
      new Paragraph({
        children: [new TextRun({ text: step.instruction, bold: true, size: 26 })],
        spacing: { after: 200 },
      })
    );

    // Embed screenshot
    if (step.screenshot_url) {
      const imgPath = path.join(UPLOADS_DIR, path.basename(step.screenshot_url));
      if (fs.existsSync(imgPath)) {
        try {
          const imgBuffer = fs.readFileSync(imgPath);
          const ext = path.extname(imgPath).replace('.', '').toLowerCase();
          const imgType = ext === 'jpg' ? 'jpeg' : ext;

          children.push(
            new Paragraph({
              children: [
                new ImageRun({
                  data: imgBuffer,
                  transformation: { width: 550, height: 330 },
                  type: imgType,
                }),
              ],
              alignment: AlignmentType.CENTER,
              spacing: { after: 200 },
            })
          );
        } catch (e) {
          // Skip unreadable image
        }
      }
    }

    if (step.page_url) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: `URL: ${step.page_url}`, color: '9ca3af', size: 18 })],
          spacing: { after: 300 },
        })
      );
    }
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
    creator: 'SnapGuide',
    title: tutorial.title,
  });

  const buffer = await Packer.toBuffer(doc);

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  res.setHeader('Content-Disposition', `attachment; filename="${sanitizeFilename(tutorial.title)}.docx"`);
  res.send(buffer);
});

// ─── Helpers ────────────────────────────────────────────────────────────────

function escapeHtml(str = '') {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function sanitizeFilename(name = 'tutorial') {
  return name.replace(/[^a-z0-9_\-\s]/gi, '_').replace(/\s+/g, '_').slice(0, 80) || 'tutorial';
}

module.exports = router;
